const traductionsEuro = {
  Equipe: "Team",
  Points: "Points",
  Played: "Joué",
  Won: "Gagné",
  Drawn: "Nul",
  Lost: "Perdu",
  "Goals For": "Buts Pour",
  "Goals Against": "Buts Contre",
  "Goal Difference": "Différence de Buts",
  Loading: "Chargement...",
  Error: "Erreur",
  Group: "Groupe ",

  Albania: "Albanie",
  Andorra: "Andorre",
  Armenia: "Arménie",
  Austria: "Autriche",
  Azerbaijan: "Azerbaïdjan",
  Belarus: "Biélorussie",
  Belgium: "Belgique",
  "Bosnia and Herzegovina": "Bosnie-Herzégovine",
  Bulgaria: "Bulgarie",
  Croatia: "Croatie",
  Cyprus: "Chypre",
  Denmark: "Danemark",
  England: "Angleterre",
  Estonia: "Estonie",
  "Faroe Islands": "Îles Féroé",
  Finland: "Finlande",
  France: "France",
  Georgia: "Géorgie",
  Germany: "Allemagne",
  Gibraltar: "Gibraltar",
  Greece: "Grèce",
  Hungary: "Hongrie",
  Iceland: "Islande",
  Ireland: "Irlande",
  Israel: "Israël",
  Italy: "Italie",
  Kazakhstan: "Kazakhstan",
  Kosovo: "Kosovo",
  Latvia: "Lettonie",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lituanie",
  Luxembourg: "Luxembourg",
  Malta: "Malte",
  Moldova: "Moldavie",
  Montenegro: "Monténégro",
  Netherlands: "Pays-Bas",
  "North Macedonia": "Macédoine du Nord",
  "Northern Ireland": "Irlande du Nord",
  Norway: "Norvège",
  Poland: "Pologne",
  Portugal: "Portugal",
  Romania: "Roumanie",
  Russia: "Russie",
  "San Marino": "Saint-Marin",
  Scotland: "Écosse",
  Serbia: "Serbie",
  Slovakia: "Slovaquie",
  Slovenia: "Slovénie",
  Spain: "Espagne",
  Sweden: "Suède",
  Switzerland: "Suisse",
  Turkey: "Turquie",
  Ukraine: "Ukraine",
  Wales: "Pays de Galles",
  Czechia: "R. tchèque",
};

export default traductionsEuro;
